package tests;

import static testUtils.LoggingMatcher.log;

import io.qameta.allure.Description;
import io.qameta.allure.Epic;
import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.hamcrest.Matchers;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import pojos.Book;
import testUtils.Assertion;

/** Test cases for updating books via the API. */
@Epic("Book Management")
@Feature("Update Book")
@Severity(SeverityLevel.NORMAL)
public class TS03_UpdateBook extends BaseTest {

  private int bookId;

  /** Creates a book before running update book tests. */
  @BeforeTest
   @Description("Creates a set of books before running update book tests to ensure data is available.")
  public void createBookBeforeUpdateBookTest() {
    Book book = new Book("PUT API Test Book Title ", "PUT API Test Book Author ");
    Book responseBook =
        RestAssured.given()
            .auth()
            .oauth2(USER_AUTH_TOKEN)
            .contentType(ContentType.JSON)
            .body(book)
            .when()
            .post()
            .then()
            .statusCode(201)
            .extract()
            .as(Book.class);
    Assertion.assertNotNull(responseBook.getId(), "Book ID should be generated by the server");
    Assertion.assertEquals(responseBook.getTitle(), book.getTitle(), "Book title should match");
    Assertion.assertEquals(responseBook.getAuthor(), book.getAuthor(), "Book author should match");

    bookId = responseBook.getId();
  }

  /** Should update the author of a book. */
  @Test
  @Description("Updates the author of an existing book and verifies the change.")
  public void shouldUpdateBookAuthor() {
    RestAssured.given()
        .contentType(ContentType.JSON)
        .auth()
        .oauth2(USER_AUTH_TOKEN)
        .pathParam("bookId", bookId)
        .body("{\"author\": \"Test PUT API Book Author Name\"}")
        .when()
        .put("/{bookId}")
        .then()
        .statusCode(200)
        .body("id", log(logger, Matchers.equalTo(bookId)))
        .body("author", log(logger, Matchers.equalTo("Test PUT API Book Author Name")));
  }

  /** Should update the title of a book. */
  @Test
  @Description("Updates the title of an existing book and verifies the change.")
  public void shouldUpdateBookTitle() {
    RestAssured.given()
        .contentType(ContentType.JSON)
        .auth()
        .oauth2(USER_AUTH_TOKEN)
        .pathParam("bookId", bookId)
        .body("{\"title\": \"Test PUT API Book Title\"}")
        .when()
        .put("/{bookId}")
        .then()
        .statusCode(200)
        .body("id", log(logger, Matchers.equalTo(bookId)))
        .body("title", log(logger, Matchers.equalTo("Test PUT API Book Title")));
  }

  /** Should return 401 when no auth is provided on update book. */
  @Test
  @Description("Attempts to update a book without authentication and expects a 401 Unauthorized error.")
  public void shouldReturn401WhenNoAuthIsProvidedOnUpdateBook() {
    RestAssured.given()
        .contentType(ContentType.JSON)
        .pathParam("bookId", bookId)
        .when()
        .put("/{bookId}")
        .then()
        .statusCode(401)
        .body("error", log(logger, Matchers.equalTo("Unauthorized. No token provided.")));
  }

  /** Should return 404 when book with ID does not exist. */
  @Test
  @Description("Attempts to update a non-existent book and expects a 404 Not Found error.")
  public void shouldReturn404WhenBookWithIdIsNotExists() {
    RestAssured.given()
        .contentType(ContentType.JSON)
        .auth()
        .oauth2(USER_AUTH_TOKEN)
        .pathParam("bookId", 890761)
        .when()
        .put("/{bookId}")
        .then()
        .statusCode(404)
        .body("error", log(logger, Matchers.equalTo("Book not found")));
  }

  /** Should return 400 when a different book ID is given in the body. */
  @Test
  @Description("Attempts to update a book with a mismatched ID in the request body and expects a 400 Bad Request error.")
  public void shouldReturn400WhenDifferentBookIdIsGivenInBody() {
    RestAssured.given()
        .contentType(ContentType.JSON)
        .auth()
        .oauth2(USER_AUTH_TOKEN)
        .pathParam("bookId", bookId)
        .body("{\"author\": \"Updated Author Name\", \"id\": 345}")
        .when()
        .put("/{bookId}")
        .then()
        .statusCode(400)
        .body("error", log(logger, Matchers.equalTo("Updating book ID is not allowed.")));
  }

  /** Should update the book when the same book ID is given in the body. */
  @Test
  @Description("Updates a book when the same book ID is provided in the request body and verifies the update.")
  public void shouldUpdateBookWhenSameBookIdIsGivenInBody() {
    Book book = new Book(bookId, "Test PUT API Book Title 2", "Test PUT API Book Author Name 2");
    Book responseBook =
        RestAssured.given()
            .contentType(ContentType.JSON)
            .auth()
            .oauth2(USER_AUTH_TOKEN)
            .pathParam("bookId", bookId)
            .body(book)
            .when()
            .put("/{bookId}")
            .then()
            .statusCode(200)
            .extract()
            .as(Book.class);
    Assertion.assertNotNull(responseBook.getId(), "Book ID should be generated by the server");
    Assertion.assertEquals(responseBook.getTitle(), book.getTitle(), "Book title should match");
    Assertion.assertEquals(responseBook.getAuthor(), book.getAuthor(), "Book author should match");
  }
}
