package tests;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.hamcrest.Matchers;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import pojos.Book;
import testUtils.Assertion;

/** Test cases for deleting books via the API. */
public class TS04_DeleteBook extends BaseTest {

  private int bookId;

  /** Creates a book before running delete book tests. */
  @BeforeTest
  public void createBookBeforeDeleteBookTest() {
    Book book = new Book("Delete API Test Book Title ", "Delete API Test Book Author ");
    Book responseBook =
        RestAssured.given()
            .auth()
            .oauth2(USER_AUTH_TOKEN)
            .contentType(ContentType.JSON)
            .body(book)
            .when()
            .post()
            .then()
            .statusCode(201)
            .extract()
            .as(Book.class);
    Assertion.assertNotNull(responseBook.getId(), "Book ID should be generated by the server");
    Assertion.assertEquals(responseBook.getTitle(), book.getTitle(), "Book title should match");
    Assertion.assertEquals(responseBook.getAuthor(), book.getAuthor(), "Book author should match");

    bookId = responseBook.getId();
  }

  /** Should return 401 when no auth token is provided on delete. */
  @Test
  public void shouldReturn401WhenNoAuthTokenProvidedOnDelete() {

    RestAssured.given()
        .pathParam("bookId", bookId)
        .when()
        .delete("/{bookId}")
        .then()
        .statusCode(401)
        .body("error", Matchers.equalTo("Unauthorized. No token provided."));
  }

  /** Should return 403 when user auth token is provided on delete. */
  @Test
  public void shouldReturn403WhenUserAuthTokenIsProvidedOnDelete() {
    RestAssured.given()
        .auth()
        .oauth2(USER_AUTH_TOKEN)
        .pathParam("bookId", bookId)
        .when()
        .delete("/{bookId}")
        .then()
        .statusCode(403)
        .body("error", Matchers.equalTo("Forbidden. Admin access required."));
  }

  /** Should delete the book when book ID is valid. */
  @Test
  public void shouldDeleteBookWhenBookIdIsValid() {
    RestAssured.given()
        .auth()
        .oauth2(USER_ADMIN_TOKEN)
        .pathParam("bookId", bookId)
        .when()
        .delete("/{bookId}")
        .then()
        .statusCode(204);
  }

  /** Should return 404 when the book is already deleted or does not exist. */
  @Test(dependsOnMethods = "shouldDeleteBookWhenBookIdIsValid")
  public void shouldReturn404WhenBookIsAlreadyDeletedOrNotExists() {
    RestAssured.given()
        .auth()
        .oauth2(USER_ADMIN_TOKEN)
        .pathParam("bookId", bookId)
        .when()
        .delete("/{bookId}")
        .then()
        .statusCode(404)
        .body("error", Matchers.equalTo("Book not found"));
  }
}
